# Generated by Django 4.1.1 on 2022-10-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
