# Generated by Django 4.1.1 on 2022-11-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_borrarpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='User',
        ),
        migrations.DeleteModel(
            name='borrarPost',
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
